//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class myResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal myResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tools.langs.myResources", typeof(myResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string addNew {
            get {
                return ResourceManager.GetString("addNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to watch list.
        /// </summary>
        internal static string addToWatchList {
            get {
                return ResourceManager.GetString("addToWatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All profit details.
        /// </summary>
        internal static string allProfitDetail {
            get {
                return ResourceManager.GetString("allProfitDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Transactions.
        /// </summary>
        internal static string allTransaction {
            get {
                return ResourceManager.GetString("allTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back testing.
        /// </summary>
        internal static string backTest {
            get {
                return ResourceManager.GetString("backTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only sell after.
        /// </summary>
        internal static string buy2SellInterval {
            get {
                return ResourceManager.GetString("buy2SellInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Amt.
        /// </summary>
        internal static string cashAmt {
            get {
                return ResourceManager.GetString("cashAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code list.
        /// </summary>
        internal static string codeList {
            get {
                return ResourceManager.GetString("codeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        internal static string criteria {
            get {
                return ResourceManager.GetString("criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved !.
        /// </summary>
        internal static string dataSaved {
            get {
                return ResourceManager.GetString("dataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        internal static string estimation {
            get {
                return ResourceManager.GetString("estimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Estimation.
        /// </summary>
        internal static string exportEstimation {
            get {
                return ResourceManager.GetString("exportEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Result.
        /// </summary>
        internal static string exportResult {
            get {
                return ResourceManager.GetString("exportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Amt.
        /// </summary>
        internal static string feeAmt {
            get {
                return ResourceManager.GetString("feeAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full View.
        /// </summary>
        internal static string fullView {
            get {
                return ResourceManager.GetString("fullView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        internal static string investment {
            get {
                return ResourceManager.GetString("investment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep sell advice.
        /// </summary>
        internal static string keepSellAdvice {
            get {
                return ResourceManager.GetString("keepSellAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max buy.
        /// </summary>
        internal static string maxBuyAmtPercent {
            get {
                return ResourceManager.GetString("maxBuyAmtPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Buy Qty.
        /// </summary>
        internal static string maxBuyQtyPercent {
            get {
                return ResourceManager.GetString("maxBuyQtyPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Qty Accumulate.
        /// </summary>
        internal static string maxQtyAccumulatePercent {
            get {
                return ResourceManager.GetString("maxQtyAccumulatePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max qty reduce.
        /// </summary>
        internal static string maxQtyReducePercent {
            get {
                return ResourceManager.GetString("maxQtyReducePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data !.
        /// </summary>
        internal static string noData {
            get {
                return ResourceManager.GetString("noData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Date.
        /// </summary>
        internal static string onDate {
            get {
                return ResourceManager.GetString("onDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string option {
            get {
                return ResourceManager.GetString("option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodicity.
        /// </summary>
        internal static string periodicity {
            get {
                return ResourceManager.GetString("periodicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price ratio.
        /// </summary>
        internal static string priceWeight {
            get {
                return ResourceManager.GetString("priceWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        internal static string profit {
            get {
                return ResourceManager.GetString("profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit details.
        /// </summary>
        internal static string profitDetail {
            get {
                return ResourceManager.GetString("profitDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string qty {
            get {
                return ResourceManager.GetString("qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string reload {
            get {
                return ResourceManager.GetString("reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening.
        /// </summary>
        internal static string screening {
            get {
                return ResourceManager.GetString("screening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Chart.
        /// </summary>
        internal static string showChart {
            get {
                return ResourceManager.GetString("showChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        internal static string strategy {
            get {
                return ResourceManager.GetString("strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy Ranking.
        /// </summary>
        internal static string strategyRanking {
            get {
                return ResourceManager.GetString("strategyRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Scale.
        /// </summary>
        internal static string timeScale {
            get {
                return ResourceManager.GetString("timeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string totalAmt {
            get {
                return ResourceManager.GetString("totalAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total capital.
        /// </summary>
        internal static string totalCapital {
            get {
                return ResourceManager.GetString("totalCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume ratio.
        /// </summary>
        internal static string volumeWeight {
            get {
                return ResourceManager.GetString("volumeWeight", resourceCulture);
            }
        }
    }
}
