//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imports.clientSSI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ssi.com.vn/", ConfigurationName="clientSSI.AjaxWebServiceSoap")]
    public interface AjaxWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetDataHoSTC2Result from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetDataHoSTC2", ReplyAction="*")]
        Imports.clientSSI.GetDataHoSTC2Response GetDataHoSTC2(Imports.clientSSI.GetDataHoSTC2Request request);
        
        // CODEGEN: Generating message contract since element name GetDataHoSTC2_IndexResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetDataHoSTC2_Index", ReplyAction="*")]
        Imports.clientSSI.GetDataHoSTC2_IndexResponse GetDataHoSTC2_Index(Imports.clientSSI.GetDataHoSTC2_IndexRequest request);
        
        // CODEGEN: Generating message contract since element name GetDataHaSTC2Result from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetDataHaSTC2", ReplyAction="*")]
        Imports.clientSSI.GetDataHaSTC2Response GetDataHaSTC2(Imports.clientSSI.GetDataHaSTC2Request request);
        
        // CODEGEN: Generating message contract since element name GetDataHaSTC2_IndexResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetDataHaSTC2_Index", ReplyAction="*")]
        Imports.clientSSI.GetDataHaSTC2_IndexResponse GetDataHaSTC2_Index(Imports.clientSSI.GetDataHaSTC2_IndexRequest request);
        
        // CODEGEN: Generating message contract since element name GetStockListHoResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetStockListHo", ReplyAction="*")]
        Imports.clientSSI.GetStockListHoResponse GetStockListHo(Imports.clientSSI.GetStockListHoRequest request);
        
        // CODEGEN: Generating message contract since element name GetStockListHaResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetStockListHa", ReplyAction="*")]
        Imports.clientSSI.GetStockListHaResponse GetStockListHa(Imports.clientSSI.GetStockListHaRequest request);
        
        // CODEGEN: Generating message contract since element name GetUpcomStockListResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomStockList", ReplyAction="*")]
        Imports.clientSSI.GetUpcomStockListResponse GetUpcomStockList(Imports.clientSSI.GetUpcomStockListRequest request);
        
        // CODEGEN: Generating message contract since element name GetUpcomIndexResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomIndex", ReplyAction="*")]
        Imports.clientSSI.GetUpcomIndexResponse GetUpcomIndex(Imports.clientSSI.GetUpcomIndexRequest request);
        
        // CODEGEN: Generating message contract since element name GetUpcomPriceResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomPrice", ReplyAction="*")]
        Imports.clientSSI.GetUpcomPriceResponse GetUpcomPrice(Imports.clientSSI.GetUpcomPriceRequest request);
        
        // CODEGEN: Generating message contract since element name GetUpcomPriorPriceResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetUpcomPriorPrice", ReplyAction="*")]
        Imports.clientSSI.GetUpcomPriorPriceResponse GetUpcomPriorPrice(Imports.clientSSI.GetUpcomPriorPriceRequest request);
        
        // CODEGEN: Generating message contract since element name GetBondOutRightMarketResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetBondOutRightMarket", ReplyAction="*")]
        Imports.clientSSI.GetBondOutRightMarketResponse GetBondOutRightMarket(Imports.clientSSI.GetBondOutRightMarketRequest request);
        
        // CODEGEN: Generating message contract since element name GetBondReposMarketResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetBondReposMarket", ReplyAction="*")]
        Imports.clientSSI.GetBondReposMarketResponse GetBondReposMarket(Imports.clientSSI.GetBondReposMarketRequest request);
        
        // CODEGEN: Generating message contract since element name GetBondOutRightResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetBondOutRight", ReplyAction="*")]
        Imports.clientSSI.GetBondOutRightResponse GetBondOutRight(Imports.clientSSI.GetBondOutRightRequest request);
        
        // CODEGEN: Generating message contract since element name GetBondReposResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetBondRepos", ReplyAction="*")]
        Imports.clientSSI.GetBondReposResponse GetBondRepos(Imports.clientSSI.GetBondReposRequest request);
        
        // CODEGEN: Generating message contract since element name GetBondStockListResult from namespace http://ssi.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ssi.com.vn/GetBondStockList", ReplyAction="*")]
        Imports.clientSSI.GetBondStockListResponse GetBondStockList(Imports.clientSSI.GetBondStockListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataHoSTC2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataHoSTC2", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetDataHoSTC2RequestBody Body;
        
        public GetDataHoSTC2Request() {
        }
        
        public GetDataHoSTC2Request(Imports.clientSSI.GetDataHoSTC2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataHoSTC2RequestBody {
        
        public GetDataHoSTC2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataHoSTC2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataHoSTC2Response", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetDataHoSTC2ResponseBody Body;
        
        public GetDataHoSTC2Response() {
        }
        
        public GetDataHoSTC2Response(Imports.clientSSI.GetDataHoSTC2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetDataHoSTC2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataHoSTC2Result;
        
        public GetDataHoSTC2ResponseBody() {
        }
        
        public GetDataHoSTC2ResponseBody(string GetDataHoSTC2Result) {
            this.GetDataHoSTC2Result = GetDataHoSTC2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataHoSTC2_IndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataHoSTC2_Index", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetDataHoSTC2_IndexRequestBody Body;
        
        public GetDataHoSTC2_IndexRequest() {
        }
        
        public GetDataHoSTC2_IndexRequest(Imports.clientSSI.GetDataHoSTC2_IndexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataHoSTC2_IndexRequestBody {
        
        public GetDataHoSTC2_IndexRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataHoSTC2_IndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataHoSTC2_IndexResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetDataHoSTC2_IndexResponseBody Body;
        
        public GetDataHoSTC2_IndexResponse() {
        }
        
        public GetDataHoSTC2_IndexResponse(Imports.clientSSI.GetDataHoSTC2_IndexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetDataHoSTC2_IndexResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataHoSTC2_IndexResult;
        
        public GetDataHoSTC2_IndexResponseBody() {
        }
        
        public GetDataHoSTC2_IndexResponseBody(string GetDataHoSTC2_IndexResult) {
            this.GetDataHoSTC2_IndexResult = GetDataHoSTC2_IndexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataHaSTC2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataHaSTC2", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetDataHaSTC2RequestBody Body;
        
        public GetDataHaSTC2Request() {
        }
        
        public GetDataHaSTC2Request(Imports.clientSSI.GetDataHaSTC2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataHaSTC2RequestBody {
        
        public GetDataHaSTC2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataHaSTC2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataHaSTC2Response", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetDataHaSTC2ResponseBody Body;
        
        public GetDataHaSTC2Response() {
        }
        
        public GetDataHaSTC2Response(Imports.clientSSI.GetDataHaSTC2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetDataHaSTC2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataHaSTC2Result;
        
        public GetDataHaSTC2ResponseBody() {
        }
        
        public GetDataHaSTC2ResponseBody(string GetDataHaSTC2Result) {
            this.GetDataHaSTC2Result = GetDataHaSTC2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataHaSTC2_IndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataHaSTC2_Index", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetDataHaSTC2_IndexRequestBody Body;
        
        public GetDataHaSTC2_IndexRequest() {
        }
        
        public GetDataHaSTC2_IndexRequest(Imports.clientSSI.GetDataHaSTC2_IndexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataHaSTC2_IndexRequestBody {
        
        public GetDataHaSTC2_IndexRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataHaSTC2_IndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataHaSTC2_IndexResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetDataHaSTC2_IndexResponseBody Body;
        
        public GetDataHaSTC2_IndexResponse() {
        }
        
        public GetDataHaSTC2_IndexResponse(Imports.clientSSI.GetDataHaSTC2_IndexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetDataHaSTC2_IndexResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataHaSTC2_IndexResult;
        
        public GetDataHaSTC2_IndexResponseBody() {
        }
        
        public GetDataHaSTC2_IndexResponseBody(string GetDataHaSTC2_IndexResult) {
            this.GetDataHaSTC2_IndexResult = GetDataHaSTC2_IndexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockListHoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockListHo", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetStockListHoRequestBody Body;
        
        public GetStockListHoRequest() {
        }
        
        public GetStockListHoRequest(Imports.clientSSI.GetStockListHoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStockListHoRequestBody {
        
        public GetStockListHoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockListHoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockListHoResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetStockListHoResponseBody Body;
        
        public GetStockListHoResponse() {
        }
        
        public GetStockListHoResponse(Imports.clientSSI.GetStockListHoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetStockListHoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStockListHoResult;
        
        public GetStockListHoResponseBody() {
        }
        
        public GetStockListHoResponseBody(string GetStockListHoResult) {
            this.GetStockListHoResult = GetStockListHoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockListHaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockListHa", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetStockListHaRequestBody Body;
        
        public GetStockListHaRequest() {
        }
        
        public GetStockListHaRequest(Imports.clientSSI.GetStockListHaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStockListHaRequestBody {
        
        public GetStockListHaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockListHaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockListHaResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetStockListHaResponseBody Body;
        
        public GetStockListHaResponse() {
        }
        
        public GetStockListHaResponse(Imports.clientSSI.GetStockListHaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetStockListHaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStockListHaResult;
        
        public GetStockListHaResponseBody() {
        }
        
        public GetStockListHaResponseBody(string GetStockListHaResult) {
            this.GetStockListHaResult = GetStockListHaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpcomStockListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpcomStockList", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetUpcomStockListRequestBody Body;
        
        public GetUpcomStockListRequest() {
        }
        
        public GetUpcomStockListRequest(Imports.clientSSI.GetUpcomStockListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUpcomStockListRequestBody {
        
        public GetUpcomStockListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpcomStockListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpcomStockListResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetUpcomStockListResponseBody Body;
        
        public GetUpcomStockListResponse() {
        }
        
        public GetUpcomStockListResponse(Imports.clientSSI.GetUpcomStockListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetUpcomStockListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUpcomStockListResult;
        
        public GetUpcomStockListResponseBody() {
        }
        
        public GetUpcomStockListResponseBody(string GetUpcomStockListResult) {
            this.GetUpcomStockListResult = GetUpcomStockListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpcomIndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpcomIndex", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetUpcomIndexRequestBody Body;
        
        public GetUpcomIndexRequest() {
        }
        
        public GetUpcomIndexRequest(Imports.clientSSI.GetUpcomIndexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUpcomIndexRequestBody {
        
        public GetUpcomIndexRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpcomIndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpcomIndexResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetUpcomIndexResponseBody Body;
        
        public GetUpcomIndexResponse() {
        }
        
        public GetUpcomIndexResponse(Imports.clientSSI.GetUpcomIndexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetUpcomIndexResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUpcomIndexResult;
        
        public GetUpcomIndexResponseBody() {
        }
        
        public GetUpcomIndexResponseBody(string GetUpcomIndexResult) {
            this.GetUpcomIndexResult = GetUpcomIndexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpcomPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpcomPrice", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetUpcomPriceRequestBody Body;
        
        public GetUpcomPriceRequest() {
        }
        
        public GetUpcomPriceRequest(Imports.clientSSI.GetUpcomPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUpcomPriceRequestBody {
        
        public GetUpcomPriceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpcomPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpcomPriceResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetUpcomPriceResponseBody Body;
        
        public GetUpcomPriceResponse() {
        }
        
        public GetUpcomPriceResponse(Imports.clientSSI.GetUpcomPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetUpcomPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUpcomPriceResult;
        
        public GetUpcomPriceResponseBody() {
        }
        
        public GetUpcomPriceResponseBody(string GetUpcomPriceResult) {
            this.GetUpcomPriceResult = GetUpcomPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpcomPriorPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpcomPriorPrice", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetUpcomPriorPriceRequestBody Body;
        
        public GetUpcomPriorPriceRequest() {
        }
        
        public GetUpcomPriorPriceRequest(Imports.clientSSI.GetUpcomPriorPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUpcomPriorPriceRequestBody {
        
        public GetUpcomPriorPriceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpcomPriorPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpcomPriorPriceResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetUpcomPriorPriceResponseBody Body;
        
        public GetUpcomPriorPriceResponse() {
        }
        
        public GetUpcomPriorPriceResponse(Imports.clientSSI.GetUpcomPriorPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetUpcomPriorPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUpcomPriorPriceResult;
        
        public GetUpcomPriorPriceResponseBody() {
        }
        
        public GetUpcomPriorPriceResponseBody(string GetUpcomPriorPriceResult) {
            this.GetUpcomPriorPriceResult = GetUpcomPriorPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondOutRightMarketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondOutRightMarket", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetBondOutRightMarketRequestBody Body;
        
        public GetBondOutRightMarketRequest() {
        }
        
        public GetBondOutRightMarketRequest(Imports.clientSSI.GetBondOutRightMarketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBondOutRightMarketRequestBody {
        
        public GetBondOutRightMarketRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondOutRightMarketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondOutRightMarketResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetBondOutRightMarketResponseBody Body;
        
        public GetBondOutRightMarketResponse() {
        }
        
        public GetBondOutRightMarketResponse(Imports.clientSSI.GetBondOutRightMarketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetBondOutRightMarketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBondOutRightMarketResult;
        
        public GetBondOutRightMarketResponseBody() {
        }
        
        public GetBondOutRightMarketResponseBody(string GetBondOutRightMarketResult) {
            this.GetBondOutRightMarketResult = GetBondOutRightMarketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondReposMarketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondReposMarket", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetBondReposMarketRequestBody Body;
        
        public GetBondReposMarketRequest() {
        }
        
        public GetBondReposMarketRequest(Imports.clientSSI.GetBondReposMarketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBondReposMarketRequestBody {
        
        public GetBondReposMarketRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondReposMarketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondReposMarketResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetBondReposMarketResponseBody Body;
        
        public GetBondReposMarketResponse() {
        }
        
        public GetBondReposMarketResponse(Imports.clientSSI.GetBondReposMarketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetBondReposMarketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBondReposMarketResult;
        
        public GetBondReposMarketResponseBody() {
        }
        
        public GetBondReposMarketResponseBody(string GetBondReposMarketResult) {
            this.GetBondReposMarketResult = GetBondReposMarketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondOutRightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondOutRight", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetBondOutRightRequestBody Body;
        
        public GetBondOutRightRequest() {
        }
        
        public GetBondOutRightRequest(Imports.clientSSI.GetBondOutRightRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBondOutRightRequestBody {
        
        public GetBondOutRightRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondOutRightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondOutRightResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetBondOutRightResponseBody Body;
        
        public GetBondOutRightResponse() {
        }
        
        public GetBondOutRightResponse(Imports.clientSSI.GetBondOutRightResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetBondOutRightResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBondOutRightResult;
        
        public GetBondOutRightResponseBody() {
        }
        
        public GetBondOutRightResponseBody(string GetBondOutRightResult) {
            this.GetBondOutRightResult = GetBondOutRightResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondReposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondRepos", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetBondReposRequestBody Body;
        
        public GetBondReposRequest() {
        }
        
        public GetBondReposRequest(Imports.clientSSI.GetBondReposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBondReposRequestBody {
        
        public GetBondReposRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondReposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondReposResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetBondReposResponseBody Body;
        
        public GetBondReposResponse() {
        }
        
        public GetBondReposResponse(Imports.clientSSI.GetBondReposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetBondReposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBondReposResult;
        
        public GetBondReposResponseBody() {
        }
        
        public GetBondReposResponseBody(string GetBondReposResult) {
            this.GetBondReposResult = GetBondReposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondStockListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondStockList", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetBondStockListRequestBody Body;
        
        public GetBondStockListRequest() {
        }
        
        public GetBondStockListRequest(Imports.clientSSI.GetBondStockListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBondStockListRequestBody {
        
        public GetBondStockListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondStockListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondStockListResponse", Namespace="http://ssi.com.vn/", Order=0)]
        public Imports.clientSSI.GetBondStockListResponseBody Body;
        
        public GetBondStockListResponse() {
        }
        
        public GetBondStockListResponse(Imports.clientSSI.GetBondStockListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ssi.com.vn/")]
    public partial class GetBondStockListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBondStockListResult;
        
        public GetBondStockListResponseBody() {
        }
        
        public GetBondStockListResponseBody(string GetBondStockListResult) {
            this.GetBondStockListResult = GetBondStockListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AjaxWebServiceSoapChannel : Imports.clientSSI.AjaxWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AjaxWebServiceSoapClient : System.ServiceModel.ClientBase<Imports.clientSSI.AjaxWebServiceSoap>, Imports.clientSSI.AjaxWebServiceSoap {
        
        public AjaxWebServiceSoapClient() {
        }
        
        public AjaxWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AjaxWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AjaxWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AjaxWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetDataHoSTC2Response Imports.clientSSI.AjaxWebServiceSoap.GetDataHoSTC2(Imports.clientSSI.GetDataHoSTC2Request request) {
            return base.Channel.GetDataHoSTC2(request);
        }
        
        public string GetDataHoSTC2() {
            Imports.clientSSI.GetDataHoSTC2Request inValue = new Imports.clientSSI.GetDataHoSTC2Request();
            inValue.Body = new Imports.clientSSI.GetDataHoSTC2RequestBody();
            Imports.clientSSI.GetDataHoSTC2Response retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetDataHoSTC2(inValue);
            return retVal.Body.GetDataHoSTC2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetDataHoSTC2_IndexResponse Imports.clientSSI.AjaxWebServiceSoap.GetDataHoSTC2_Index(Imports.clientSSI.GetDataHoSTC2_IndexRequest request) {
            return base.Channel.GetDataHoSTC2_Index(request);
        }
        
        public string GetDataHoSTC2_Index() {
            Imports.clientSSI.GetDataHoSTC2_IndexRequest inValue = new Imports.clientSSI.GetDataHoSTC2_IndexRequest();
            inValue.Body = new Imports.clientSSI.GetDataHoSTC2_IndexRequestBody();
            Imports.clientSSI.GetDataHoSTC2_IndexResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetDataHoSTC2_Index(inValue);
            return retVal.Body.GetDataHoSTC2_IndexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetDataHaSTC2Response Imports.clientSSI.AjaxWebServiceSoap.GetDataHaSTC2(Imports.clientSSI.GetDataHaSTC2Request request) {
            return base.Channel.GetDataHaSTC2(request);
        }
        
        public string GetDataHaSTC2() {
            Imports.clientSSI.GetDataHaSTC2Request inValue = new Imports.clientSSI.GetDataHaSTC2Request();
            inValue.Body = new Imports.clientSSI.GetDataHaSTC2RequestBody();
            Imports.clientSSI.GetDataHaSTC2Response retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetDataHaSTC2(inValue);
            return retVal.Body.GetDataHaSTC2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetDataHaSTC2_IndexResponse Imports.clientSSI.AjaxWebServiceSoap.GetDataHaSTC2_Index(Imports.clientSSI.GetDataHaSTC2_IndexRequest request) {
            return base.Channel.GetDataHaSTC2_Index(request);
        }
        
        public string GetDataHaSTC2_Index() {
            Imports.clientSSI.GetDataHaSTC2_IndexRequest inValue = new Imports.clientSSI.GetDataHaSTC2_IndexRequest();
            inValue.Body = new Imports.clientSSI.GetDataHaSTC2_IndexRequestBody();
            Imports.clientSSI.GetDataHaSTC2_IndexResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetDataHaSTC2_Index(inValue);
            return retVal.Body.GetDataHaSTC2_IndexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetStockListHoResponse Imports.clientSSI.AjaxWebServiceSoap.GetStockListHo(Imports.clientSSI.GetStockListHoRequest request) {
            return base.Channel.GetStockListHo(request);
        }
        
        public string GetStockListHo() {
            Imports.clientSSI.GetStockListHoRequest inValue = new Imports.clientSSI.GetStockListHoRequest();
            inValue.Body = new Imports.clientSSI.GetStockListHoRequestBody();
            Imports.clientSSI.GetStockListHoResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetStockListHo(inValue);
            return retVal.Body.GetStockListHoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetStockListHaResponse Imports.clientSSI.AjaxWebServiceSoap.GetStockListHa(Imports.clientSSI.GetStockListHaRequest request) {
            return base.Channel.GetStockListHa(request);
        }
        
        public string GetStockListHa() {
            Imports.clientSSI.GetStockListHaRequest inValue = new Imports.clientSSI.GetStockListHaRequest();
            inValue.Body = new Imports.clientSSI.GetStockListHaRequestBody();
            Imports.clientSSI.GetStockListHaResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetStockListHa(inValue);
            return retVal.Body.GetStockListHaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetUpcomStockListResponse Imports.clientSSI.AjaxWebServiceSoap.GetUpcomStockList(Imports.clientSSI.GetUpcomStockListRequest request) {
            return base.Channel.GetUpcomStockList(request);
        }
        
        public string GetUpcomStockList() {
            Imports.clientSSI.GetUpcomStockListRequest inValue = new Imports.clientSSI.GetUpcomStockListRequest();
            inValue.Body = new Imports.clientSSI.GetUpcomStockListRequestBody();
            Imports.clientSSI.GetUpcomStockListResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetUpcomStockList(inValue);
            return retVal.Body.GetUpcomStockListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetUpcomIndexResponse Imports.clientSSI.AjaxWebServiceSoap.GetUpcomIndex(Imports.clientSSI.GetUpcomIndexRequest request) {
            return base.Channel.GetUpcomIndex(request);
        }
        
        public string GetUpcomIndex() {
            Imports.clientSSI.GetUpcomIndexRequest inValue = new Imports.clientSSI.GetUpcomIndexRequest();
            inValue.Body = new Imports.clientSSI.GetUpcomIndexRequestBody();
            Imports.clientSSI.GetUpcomIndexResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetUpcomIndex(inValue);
            return retVal.Body.GetUpcomIndexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetUpcomPriceResponse Imports.clientSSI.AjaxWebServiceSoap.GetUpcomPrice(Imports.clientSSI.GetUpcomPriceRequest request) {
            return base.Channel.GetUpcomPrice(request);
        }
        
        public string GetUpcomPrice() {
            Imports.clientSSI.GetUpcomPriceRequest inValue = new Imports.clientSSI.GetUpcomPriceRequest();
            inValue.Body = new Imports.clientSSI.GetUpcomPriceRequestBody();
            Imports.clientSSI.GetUpcomPriceResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetUpcomPrice(inValue);
            return retVal.Body.GetUpcomPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetUpcomPriorPriceResponse Imports.clientSSI.AjaxWebServiceSoap.GetUpcomPriorPrice(Imports.clientSSI.GetUpcomPriorPriceRequest request) {
            return base.Channel.GetUpcomPriorPrice(request);
        }
        
        public string GetUpcomPriorPrice() {
            Imports.clientSSI.GetUpcomPriorPriceRequest inValue = new Imports.clientSSI.GetUpcomPriorPriceRequest();
            inValue.Body = new Imports.clientSSI.GetUpcomPriorPriceRequestBody();
            Imports.clientSSI.GetUpcomPriorPriceResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetUpcomPriorPrice(inValue);
            return retVal.Body.GetUpcomPriorPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetBondOutRightMarketResponse Imports.clientSSI.AjaxWebServiceSoap.GetBondOutRightMarket(Imports.clientSSI.GetBondOutRightMarketRequest request) {
            return base.Channel.GetBondOutRightMarket(request);
        }
        
        public string GetBondOutRightMarket() {
            Imports.clientSSI.GetBondOutRightMarketRequest inValue = new Imports.clientSSI.GetBondOutRightMarketRequest();
            inValue.Body = new Imports.clientSSI.GetBondOutRightMarketRequestBody();
            Imports.clientSSI.GetBondOutRightMarketResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetBondOutRightMarket(inValue);
            return retVal.Body.GetBondOutRightMarketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetBondReposMarketResponse Imports.clientSSI.AjaxWebServiceSoap.GetBondReposMarket(Imports.clientSSI.GetBondReposMarketRequest request) {
            return base.Channel.GetBondReposMarket(request);
        }
        
        public string GetBondReposMarket() {
            Imports.clientSSI.GetBondReposMarketRequest inValue = new Imports.clientSSI.GetBondReposMarketRequest();
            inValue.Body = new Imports.clientSSI.GetBondReposMarketRequestBody();
            Imports.clientSSI.GetBondReposMarketResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetBondReposMarket(inValue);
            return retVal.Body.GetBondReposMarketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetBondOutRightResponse Imports.clientSSI.AjaxWebServiceSoap.GetBondOutRight(Imports.clientSSI.GetBondOutRightRequest request) {
            return base.Channel.GetBondOutRight(request);
        }
        
        public string GetBondOutRight() {
            Imports.clientSSI.GetBondOutRightRequest inValue = new Imports.clientSSI.GetBondOutRightRequest();
            inValue.Body = new Imports.clientSSI.GetBondOutRightRequestBody();
            Imports.clientSSI.GetBondOutRightResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetBondOutRight(inValue);
            return retVal.Body.GetBondOutRightResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetBondReposResponse Imports.clientSSI.AjaxWebServiceSoap.GetBondRepos(Imports.clientSSI.GetBondReposRequest request) {
            return base.Channel.GetBondRepos(request);
        }
        
        public string GetBondRepos() {
            Imports.clientSSI.GetBondReposRequest inValue = new Imports.clientSSI.GetBondReposRequest();
            inValue.Body = new Imports.clientSSI.GetBondReposRequestBody();
            Imports.clientSSI.GetBondReposResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetBondRepos(inValue);
            return retVal.Body.GetBondReposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientSSI.GetBondStockListResponse Imports.clientSSI.AjaxWebServiceSoap.GetBondStockList(Imports.clientSSI.GetBondStockListRequest request) {
            return base.Channel.GetBondStockList(request);
        }
        
        public string GetBondStockList() {
            Imports.clientSSI.GetBondStockListRequest inValue = new Imports.clientSSI.GetBondStockListRequest();
            inValue.Body = new Imports.clientSSI.GetBondStockListRequestBody();
            Imports.clientSSI.GetBondStockListResponse retVal = ((Imports.clientSSI.AjaxWebServiceSoap)(this)).GetBondStockList(inValue);
            return retVal.Body.GetBondStockListResult;
        }
    }
}
