//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imports.clientHOSE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="clientHOSE.HoSTC_ServiceSoap")]
    public interface HoSTC_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetLiveSecurityResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLiveSecurity", ReplyAction="*")]
        Imports.clientHOSE.GetLiveSecurityResponse GetLiveSecurity(Imports.clientHOSE.GetLiveSecurityRequest request);
        
        // CODEGEN: Generating message contract since element name fPUT_THROUGHTResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fPUT_THROUGHT", ReplyAction="*")]
        Imports.clientHOSE.fPUT_THROUGHTResponse fPUT_THROUGHT(Imports.clientHOSE.fPUT_THROUGHTRequest request);
        
        // CODEGEN: Generating message contract since element name fGetSTOCKROOMResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fGetSTOCKROOM", ReplyAction="*")]
        Imports.clientHOSE.fGetSTOCKROOMResponse fGetSTOCKROOM(Imports.clientHOSE.fGetSTOCKROOMRequest request);
        
        // CODEGEN: Generating message contract since element name fUserOnlineResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fUserOnline", ReplyAction="*")]
        Imports.clientHOSE.fUserOnlineResponse fUserOnline(Imports.clientHOSE.fUserOnlineRequest request);
        
        // CODEGEN: Generating message contract since element name GetLiveTotalMKTResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLiveTotalMKT", ReplyAction="*")]
        Imports.clientHOSE.GetLiveTotalMKTResponse GetLiveTotalMKT(Imports.clientHOSE.GetLiveTotalMKTRequest request);
        
        // CODEGEN: Generating message contract since element name GetListStockWarningResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListStockWarning", ReplyAction="*")]
        Imports.clientHOSE.GetListStockWarningResponse GetListStockWarning(Imports.clientHOSE.GetListStockWarningRequest request);
        
        // CODEGEN: Generating message contract since element name GetList30StockResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList30Stock", ReplyAction="*")]
        Imports.clientHOSE.GetList30StockResponse GetList30Stock(Imports.clientHOSE.GetList30StockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveSecurityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveSecurity", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.GetLiveSecurityRequestBody Body;
        
        public GetLiveSecurityRequest() {
        }
        
        public GetLiveSecurityRequest(Imports.clientHOSE.GetLiveSecurityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLiveSecurityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool f_time;
        
        public GetLiveSecurityRequestBody() {
        }
        
        public GetLiveSecurityRequestBody(bool f_time) {
            this.f_time = f_time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveSecurityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveSecurityResponse", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.GetLiveSecurityResponseBody Body;
        
        public GetLiveSecurityResponse() {
        }
        
        public GetLiveSecurityResponse(Imports.clientHOSE.GetLiveSecurityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLiveSecurityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLiveSecurityResult;
        
        public GetLiveSecurityResponseBody() {
        }
        
        public GetLiveSecurityResponseBody(string GetLiveSecurityResult) {
            this.GetLiveSecurityResult = GetLiveSecurityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fPUT_THROUGHTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fPUT_THROUGHT", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.fPUT_THROUGHTRequestBody Body;
        
        public fPUT_THROUGHTRequest() {
        }
        
        public fPUT_THROUGHTRequest(Imports.clientHOSE.fPUT_THROUGHTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class fPUT_THROUGHTRequestBody {
        
        public fPUT_THROUGHTRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fPUT_THROUGHTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fPUT_THROUGHTResponse", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.fPUT_THROUGHTResponseBody Body;
        
        public fPUT_THROUGHTResponse() {
        }
        
        public fPUT_THROUGHTResponse(Imports.clientHOSE.fPUT_THROUGHTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fPUT_THROUGHTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fPUT_THROUGHTResult;
        
        public fPUT_THROUGHTResponseBody() {
        }
        
        public fPUT_THROUGHTResponseBody(string fPUT_THROUGHTResult) {
            this.fPUT_THROUGHTResult = fPUT_THROUGHTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fGetSTOCKROOMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fGetSTOCKROOM", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.fGetSTOCKROOMRequestBody Body;
        
        public fGetSTOCKROOMRequest() {
        }
        
        public fGetSTOCKROOMRequest(Imports.clientHOSE.fGetSTOCKROOMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class fGetSTOCKROOMRequestBody {
        
        public fGetSTOCKROOMRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fGetSTOCKROOMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fGetSTOCKROOMResponse", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.fGetSTOCKROOMResponseBody Body;
        
        public fGetSTOCKROOMResponse() {
        }
        
        public fGetSTOCKROOMResponse(Imports.clientHOSE.fGetSTOCKROOMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fGetSTOCKROOMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fGetSTOCKROOMResult;
        
        public fGetSTOCKROOMResponseBody() {
        }
        
        public fGetSTOCKROOMResponseBody(string fGetSTOCKROOMResult) {
            this.fGetSTOCKROOMResult = fGetSTOCKROOMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fUserOnlineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fUserOnline", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.fUserOnlineRequestBody Body;
        
        public fUserOnlineRequest() {
        }
        
        public fUserOnlineRequest(Imports.clientHOSE.fUserOnlineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class fUserOnlineRequestBody {
        
        public fUserOnlineRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fUserOnlineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fUserOnlineResponse", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.fUserOnlineResponseBody Body;
        
        public fUserOnlineResponse() {
        }
        
        public fUserOnlineResponse(Imports.clientHOSE.fUserOnlineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fUserOnlineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fUserOnlineResult;
        
        public fUserOnlineResponseBody() {
        }
        
        public fUserOnlineResponseBody(string fUserOnlineResult) {
            this.fUserOnlineResult = fUserOnlineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveTotalMKTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveTotalMKT", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.GetLiveTotalMKTRequestBody Body;
        
        public GetLiveTotalMKTRequest() {
        }
        
        public GetLiveTotalMKTRequest(Imports.clientHOSE.GetLiveTotalMKTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLiveTotalMKTRequestBody {
        
        public GetLiveTotalMKTRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveTotalMKTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveTotalMKTResponse", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.GetLiveTotalMKTResponseBody Body;
        
        public GetLiveTotalMKTResponse() {
        }
        
        public GetLiveTotalMKTResponse(Imports.clientHOSE.GetLiveTotalMKTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLiveTotalMKTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLiveTotalMKTResult;
        
        public GetLiveTotalMKTResponseBody() {
        }
        
        public GetLiveTotalMKTResponseBody(string GetLiveTotalMKTResult) {
            this.GetLiveTotalMKTResult = GetLiveTotalMKTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListStockWarningRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListStockWarning", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.GetListStockWarningRequestBody Body;
        
        public GetListStockWarningRequest() {
        }
        
        public GetListStockWarningRequest(Imports.clientHOSE.GetListStockWarningRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListStockWarningRequestBody {
        
        public GetListStockWarningRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListStockWarningResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListStockWarningResponse", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.GetListStockWarningResponseBody Body;
        
        public GetListStockWarningResponse() {
        }
        
        public GetListStockWarningResponse(Imports.clientHOSE.GetListStockWarningResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListStockWarningResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListStockWarningResult;
        
        public GetListStockWarningResponseBody() {
        }
        
        public GetListStockWarningResponseBody(string GetListStockWarningResult) {
            this.GetListStockWarningResult = GetListStockWarningResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetList30StockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList30Stock", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.GetList30StockRequestBody Body;
        
        public GetList30StockRequest() {
        }
        
        public GetList30StockRequest(Imports.clientHOSE.GetList30StockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetList30StockRequestBody {
        
        public GetList30StockRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetList30StockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList30StockResponse", Namespace="http://tempuri.org/", Order=0)]
        public Imports.clientHOSE.GetList30StockResponseBody Body;
        
        public GetList30StockResponse() {
        }
        
        public GetList30StockResponse(Imports.clientHOSE.GetList30StockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetList30StockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetList30StockResult;
        
        public GetList30StockResponseBody() {
        }
        
        public GetList30StockResponseBody(string GetList30StockResult) {
            this.GetList30StockResult = GetList30StockResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HoSTC_ServiceSoapChannel : Imports.clientHOSE.HoSTC_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoSTC_ServiceSoapClient : System.ServiceModel.ClientBase<Imports.clientHOSE.HoSTC_ServiceSoap>, Imports.clientHOSE.HoSTC_ServiceSoap {
        
        public HoSTC_ServiceSoapClient() {
        }
        
        public HoSTC_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HoSTC_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoSTC_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoSTC_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientHOSE.GetLiveSecurityResponse Imports.clientHOSE.HoSTC_ServiceSoap.GetLiveSecurity(Imports.clientHOSE.GetLiveSecurityRequest request) {
            return base.Channel.GetLiveSecurity(request);
        }
        
        public string GetLiveSecurity(bool f_time) {
            Imports.clientHOSE.GetLiveSecurityRequest inValue = new Imports.clientHOSE.GetLiveSecurityRequest();
            inValue.Body = new Imports.clientHOSE.GetLiveSecurityRequestBody();
            inValue.Body.f_time = f_time;
            Imports.clientHOSE.GetLiveSecurityResponse retVal = ((Imports.clientHOSE.HoSTC_ServiceSoap)(this)).GetLiveSecurity(inValue);
            return retVal.Body.GetLiveSecurityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientHOSE.fPUT_THROUGHTResponse Imports.clientHOSE.HoSTC_ServiceSoap.fPUT_THROUGHT(Imports.clientHOSE.fPUT_THROUGHTRequest request) {
            return base.Channel.fPUT_THROUGHT(request);
        }
        
        public string fPUT_THROUGHT() {
            Imports.clientHOSE.fPUT_THROUGHTRequest inValue = new Imports.clientHOSE.fPUT_THROUGHTRequest();
            inValue.Body = new Imports.clientHOSE.fPUT_THROUGHTRequestBody();
            Imports.clientHOSE.fPUT_THROUGHTResponse retVal = ((Imports.clientHOSE.HoSTC_ServiceSoap)(this)).fPUT_THROUGHT(inValue);
            return retVal.Body.fPUT_THROUGHTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientHOSE.fGetSTOCKROOMResponse Imports.clientHOSE.HoSTC_ServiceSoap.fGetSTOCKROOM(Imports.clientHOSE.fGetSTOCKROOMRequest request) {
            return base.Channel.fGetSTOCKROOM(request);
        }
        
        public string fGetSTOCKROOM() {
            Imports.clientHOSE.fGetSTOCKROOMRequest inValue = new Imports.clientHOSE.fGetSTOCKROOMRequest();
            inValue.Body = new Imports.clientHOSE.fGetSTOCKROOMRequestBody();
            Imports.clientHOSE.fGetSTOCKROOMResponse retVal = ((Imports.clientHOSE.HoSTC_ServiceSoap)(this)).fGetSTOCKROOM(inValue);
            return retVal.Body.fGetSTOCKROOMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientHOSE.fUserOnlineResponse Imports.clientHOSE.HoSTC_ServiceSoap.fUserOnline(Imports.clientHOSE.fUserOnlineRequest request) {
            return base.Channel.fUserOnline(request);
        }
        
        public string fUserOnline() {
            Imports.clientHOSE.fUserOnlineRequest inValue = new Imports.clientHOSE.fUserOnlineRequest();
            inValue.Body = new Imports.clientHOSE.fUserOnlineRequestBody();
            Imports.clientHOSE.fUserOnlineResponse retVal = ((Imports.clientHOSE.HoSTC_ServiceSoap)(this)).fUserOnline(inValue);
            return retVal.Body.fUserOnlineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientHOSE.GetLiveTotalMKTResponse Imports.clientHOSE.HoSTC_ServiceSoap.GetLiveTotalMKT(Imports.clientHOSE.GetLiveTotalMKTRequest request) {
            return base.Channel.GetLiveTotalMKT(request);
        }
        
        public string GetLiveTotalMKT() {
            Imports.clientHOSE.GetLiveTotalMKTRequest inValue = new Imports.clientHOSE.GetLiveTotalMKTRequest();
            inValue.Body = new Imports.clientHOSE.GetLiveTotalMKTRequestBody();
            Imports.clientHOSE.GetLiveTotalMKTResponse retVal = ((Imports.clientHOSE.HoSTC_ServiceSoap)(this)).GetLiveTotalMKT(inValue);
            return retVal.Body.GetLiveTotalMKTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientHOSE.GetListStockWarningResponse Imports.clientHOSE.HoSTC_ServiceSoap.GetListStockWarning(Imports.clientHOSE.GetListStockWarningRequest request) {
            return base.Channel.GetListStockWarning(request);
        }
        
        public string GetListStockWarning() {
            Imports.clientHOSE.GetListStockWarningRequest inValue = new Imports.clientHOSE.GetListStockWarningRequest();
            inValue.Body = new Imports.clientHOSE.GetListStockWarningRequestBody();
            Imports.clientHOSE.GetListStockWarningResponse retVal = ((Imports.clientHOSE.HoSTC_ServiceSoap)(this)).GetListStockWarning(inValue);
            return retVal.Body.GetListStockWarningResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imports.clientHOSE.GetList30StockResponse Imports.clientHOSE.HoSTC_ServiceSoap.GetList30Stock(Imports.clientHOSE.GetList30StockRequest request) {
            return base.Channel.GetList30Stock(request);
        }
        
        public string GetList30Stock() {
            Imports.clientHOSE.GetList30StockRequest inValue = new Imports.clientHOSE.GetList30StockRequest();
            inValue.Body = new Imports.clientHOSE.GetList30StockRequestBody();
            Imports.clientHOSE.GetList30StockResponse retVal = ((Imports.clientHOSE.HoSTC_ServiceSoap)(this)).GetList30Stock(inValue);
            return retVal.Body.GetList30StockResult;
        }
    }
}
