//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class myResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal myResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("client.langs.myResources", typeof(myResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back testing.
        /// </summary>
        internal static string backTesting {
            get {
                return ResourceManager.GetString("backTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string barChart {
            get {
                return ResourceManager.GetString("barChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandleSticks.
        /// </summary>
        internal static string candleSticks {
            get {
                return ResourceManager.GetString("candleSticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        internal static string chart {
            get {
                return ResourceManager.GetString("chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart grid.
        /// </summary>
        internal static string chartGrid {
            get {
                return ResourceManager.GetString("chartGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart property.
        /// </summary>
        internal static string chartProperty {
            get {
                return ResourceManager.GetString("chartProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart volume.
        /// </summary>
        internal static string chartVolume {
            get {
                return ResourceManager.GetString("chartVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        internal static string closeAll {
            get {
                return ResourceManager.GetString("closeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close .
        /// </summary>
        internal static string closeChart {
            get {
                return ResourceManager.GetString("closeChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company list.
        /// </summary>
        internal static string companyList {
            get {
                return ResourceManager.GetString("companyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string contents {
            get {
                return ResourceManager.GetString("contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator.
        /// </summary>
        internal static string indicator {
            get {
                return ResourceManager.GetString("indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line chart.
        /// </summary>
        internal static string lineChart {
            get {
                return ResourceManager.GetString("lineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string logOut {
            get {
                return ResourceManager.GetString("logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market watch.
        /// </summary>
        internal static string marketWatch {
            get {
                return ResourceManager.GetString("marketWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My portfolio.
        /// </summary>
        internal static string myPortfolio {
            get {
                return ResourceManager.GetString("myPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string myProfile {
            get {
                return ResourceManager.GetString("myProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New chart.
        /// </summary>
        internal static string newChart {
            get {
                return ResourceManager.GetString("newChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodicity.
        /// </summary>
        internal static string periodicity {
            get {
                return ResourceManager.GetString("periodicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preview.
        /// </summary>
        internal static string printPreview {
            get {
                return ResourceManager.GetString("printPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print setup.
        /// </summary>
        internal static string printSetup {
            get {
                return ResourceManager.GetString("printSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening.
        /// </summary>
        internal static string screening {
            get {
                return ResourceManager.GetString("screening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening options.
        /// </summary>
        internal static string screeningOption {
            get {
                return ResourceManager.GetString("screeningOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string selectAll {
            get {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string standard {
            get {
                return ResourceManager.GetString("standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        internal static string strategy {
            get {
                return ResourceManager.GetString("strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy options.
        /// </summary>
        internal static string strategyOption {
            get {
                return ResourceManager.GetString("strategyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy ranking.
        /// </summary>
        internal static string strategyRanking {
            get {
                return ResourceManager.GetString("strategyRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string toolAllOptions {
            get {
                return ResourceManager.GetString("toolAllOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        internal static string toolBar {
            get {
                return ResourceManager.GetString("toolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool options.
        /// </summary>
        internal static string toolOption {
            get {
                return ResourceManager.GetString("toolOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade alerts.
        /// </summary>
        internal static string tradeAlert {
            get {
                return ResourceManager.GetString("tradeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction history.
        /// </summary>
        internal static string transHistory {
            get {
                return ResourceManager.GetString("transHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undo.
        /// </summary>
        internal static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string vietnamese {
            get {
                return ResourceManager.GetString("vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string windows {
            get {
                return ResourceManager.GetString("windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string zoomIn {
            get {
                return ResourceManager.GetString("zoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string zoomOut {
            get {
                return ResourceManager.GetString("zoomOut", resourceCulture);
            }
        }
    }
}
